[project]
name = "mcr_example"
version = "0.1.0"
requires-python = ">= 3.13.2"
dependencies = [
    "branca>=0.8.2",
    "folium>=0.20.0",
    "geopandas>=1.1.2",
    "mapclassify>=2.10.0",
    "matplotlib>=3.10.8",
    "session-info>=1.0.1",
]
